### PR TITLE
Convert client/javascript to NPM project with ES5 #567

### PR DESCRIPTION
**Pull request by tadayosi**
This is my first attempt to convert the client js library to npm package. What's done here:

- Set up `client/javascript` as npm package named "jolokia.js" (it is because other names are already used, such as "jolokia", "jolokia-client", and "jolokia-js" is too similar to existing name "jolokia.js" which I own).
- Only updated the UMD part of the scripts `jolokia.js`, `jolokia-simple.js`, and `jolokia-cubism.js`, to make them importable from a Node project in CommonJS form.
- Added `"use strict";` to the js scripts to ensure it's compatible with ES5. Minimum supported JS version is ES5.
- Removed dependency to JSON2.js as `JSON.stringify()` should be available with ES5.
- Added very basic Jest tests.
- Explicitly define `jquery` as a required dependency, and `cubism` as an optional peer dependency in package.json.

TODO:

- Define `.d.ts` for TypeScript projects
- Try to remove as many usages of jQuery as possible, replacing it with Fetch API

### CODE REVIEW

**Comment by tadayosi** [comment]
Here is the view of the new `jolokia.js` package I published in advance for testing.
https://www.npmjs.com/package/jolokia.js/v/2.0.0-dev.2

**Review by grgrzybek — APPROVED** [review]
This looks great!

**Comment by tadayosi** [comment]
There's an issue with importing the library from Node.js. I'll fix it before merging it.

**Comment by grgrzybek** [comment]
Sure sure - take your time. It'll take me some time to finish the Jakarta migration.

**Comment by tadayosi** [comment]
Let me go ahead and merge this.

**Pull request merged**
