### PR TITLE
Compatibility with JakartaEE whilst maintaining backwards compatibility

### PR DESCRIPTION
**Pull request by ftrossbach**
Signed-off-by: Florian Troßbach <trossbach@gmail.com>

# Changes
I've recently come across this issue and went through the excellent discussion between @rhuss and @agebhar1 at https://github.com/rhuss/jolokia/pull/484. As I had a rough idea of what needs doing and a small bit of time on my hands, I thought I'd have a go. 
What I did:
- additional maven modules `core-servlet4` and `core-jakarta` which contains the few things from `jolokia-core` that depended on `javax` classes
- moved `war` to `war-servlet4` and `war-unsecured` to `war-servlet4-unsecured`
- created `war-jakarta` and `war-jakarta-unsecured`
- changed maven dependencies from  `jolokia-core` to either `jolokia-core-servlet4` or `jolokia-core-jakarta`, whichever applied
- some minor changes in the test setup (mainly in `jolokia-core-servlet4`)
- move to version 2.0.0-SNAPSHOT
- no changes to configured java versions

This is my interpretation of the discussions in the other pull request, mainly https://github.com/rhuss/jolokia/pull/484#issuecomment-1321174144

I made one change in that I did not keep the `war` and `war-unsecured` modules named as is for the reason that this is a breaking change and I'd want users to realize this as early as possible

/kind api-change

This adresses https://github.com/rhuss/jolokia/issues/451

### CODE REVIEW

**Comment by rhuss** [comment]
Awesome, thanks a lot! Sorry that I just waded through my GitHub backlog and discovered the PR. Unfortunately I'm still busy this week (and off next week), but a review of this PR is high on my list, and I hope we get the flying asap, as this is really an important topic.

**Comment by nhmarujo** [comment]
Hi. Any ETA for this to move forward? Thank you

**Comment by mrit** [comment]
🆙

**Comment by iagosaito** [comment]
:up:

**Comment by grgrzybek** [comment]
#451 is officially solved and as shown under https://github.com/jolokia/jolokia/issues/472#issuecomment-1738752423, Jolokia 2.0 can now run on Tomcat 10 (Servlet API 5+).

By _maintaining backwards compatibility_ we mean this:
* Jolokia 2.0 will be using JDK11, Servlet API 5+ (JakartaEE 9)
* Jolokia 1.x will be compatible with JDK1.6+, Servlet API 4 (JavaEE 8)

For some time we're going to maintain both lines. Trying to support both Servlet APIs within single Jolokia version has more drawbacks than benefits.

**Pull request closed without merging**
