### PR TITLE
Port of JMX Adapter to 2.0 branch

### PR DESCRIPTION
**Pull request by rhuss**
@skarsaune this is a port to the new 2.0 structure. You might want to have a look before I'm merging. 

wrt/ to the `forgiving` flag in the converters: What do you think to make it always forgiving ? This would make things a bit easier, and I don't think it's very harmful. Wdyt ?

### CODE REVIEW

**Comment by tadayosi** [comment]
@rhuss @skarsaune @grgrzybek @apupier It's old but it seems still we should have it for 2.0. Why not just going ahead and merge it?

**Review by tadayosi — APPROVED** [review]

**Review by grgrzybek — APPROVED** [review]

**Comment by tadayosi** [comment]
> It has probably been falling behind quite a bit. Have the plans for 2.0 been properly discussed?

@skarsaune We discussed it internally, and if I'm not mistaken we target 2.0 for Jakarta EE 10 support. I'll later create a github discussion to discuss 2.0 plan publicly further. Please join the discussion.

**Comment by skarsaune** [comment]
I see. I should probably get it aligned with master anyway, as it will be easier to keep both streams in sync, if we start out in sync. My availability over the summer is a bit limited. My timezone throughout July will be Taiwan.

**Comment by grgrzybek** [comment]
It was merged to `master` (1.x) in e969126e:
```
$ git branch --contains e969126e
* 2.0
+ master

$ git tag --contains e969126e
v1.7.0
v1.7.1
v1.7.2
```

I'm working on #557 which is about porting 1.x changes to current 2.0 branch, so I'm closing this one. Locally I see the changes in 2.0 branch.

**Pull request closed without merging**
