### PR TITLE
Sketch how to upgrade main to JakartaEE 10

### PR DESCRIPTION
**Pull request by ohumbel**
This pull request sketches what would need to be done to upgrade the `main` branch to Jakarta EE 10.

Open issues:

1. The OSGI modules are commented out, because I was not able to prevent `javax.servlet` from leaking in
(no matter how hard I tried)
2. The two naming tests in `J4pReadIntegrationTest` are disabled.

Apart from these, `mvn package` succeeds, when running with Java 17.

### CODE REVIEW

**Comment by ohumbel** [comment]
Questions:

1. Would it be OK to switch to Java 17 as a minimum?
2. Would someone be willing to help with OSGI?

**Comment by grgrzybek** [comment]
@ohumbel thanks for this huge PR, but I'm afraid I have to point you to 2.0 branch of Jolokia, where JakartaEE 9 (Servlet API 5) is being done...
We've carefully backported everything that was needed from 1.x (main branch) to 2.0. Please look at https://github.com/jolokia/jolokia/commits/2.0

**Comment by tadayosi** [comment]
@ohumbel Jakarta EE 9+ support is already done at 2.0 branch and will be released soon. Please have a look at the branch.

**Comment by grgrzybek** [comment]
@ohumbel answering your questions:

> Would it be OK to switch to Java 17 as a minimum?

We've decided to stay at JDK 11 (and of course JDK 17 should be supported), with the exception of Spring 6 dependent modules

> Would someone be willing to help with OSGI?

I will. HttpService approach will be replaced ([it already is](https://github.com/jolokia/jolokia/blob/v2.0.0-M4-2/server/core/src/main/java/org/jolokia/server/core/osgi/OsgiAgentActivator.java#L288-L313)) with Whiteboard approach, but I wait for Pax Web 10 (and Jetty 12 fixes)

**Comment by ohumbel** [comment]
@grgrzybek @tadayosi Thanks for your responses!

**Comment by ohumbel** [comment]
@grgrzybek Reiterating over Java 11 and Jetty 12 (Please forgive my naiveness - I am learning the hard way).

> We've decided to stay at JDK 11 (and of course JDK 17 should be supported), with the exception of Spring 6 dependent modules
> I will. HttpService approach will be replaced ([it already is](https://github.com/jolokia/jolokia/blob/v2.0.0-M4-2/server/core/src/main/java/org/jolokia/server/core/osgi/OsgiAgentActivator.java#L288-L313)) with Whiteboard approach, but I wait for Pax Web 10 (and Jetty 12 fixes)

The 2.0 branch uses `<version.jetty>11.0.16</version.jetty>`.
On my branch, I used jetty 12.0.1. Compiling with Java 11, I get:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project jolokia-jvm: Compilation failure: Compilation failure: 
[ERROR] /Users/oti/stuff/gitrepo/ohumbel/ohumbel/jolokia/agent/jvm/src/test/java/org/jolokia/jvmagent/security/DelegatingAuthenticatorTest.java:[28,32] cannot access org.eclipse.jetty.server.Server
[ERROR]   bad class file: /Users/oti/.m2/repository/org/eclipse/jetty/jetty-server/12.0.1/jetty-server-12.0.1.jar(/org/eclipse/jetty/server/Server.class)
[ERROR]     class file has wrong version 61.0, should be 55.0
[ERROR] /Users/oti/stuff/gitrepo/ohumbel/ohumbel/jolokia/agent/jvm/src/test/java/org/jolokia/jvmagent/security/DelegatingAuthenticatorTest.java:[30,38] cannot access org.eclipse.jetty.ee10.servlet.ServletContextHandler
[ERROR]   bad class file: /Users/oti/.m2/repository/org/eclipse/jetty/ee10/jetty-ee10-servlet/12.0.1/jetty-ee10-servlet-12.0.1.jar(/org/eclipse/jetty/ee10/servlet/ServletContextHandler.class)
[ERROR]     class file has wrong version 61.0, should be 55.0
```
You mentioned "waiting for Jetty 12 fixes" - so I wonder how you intend to compile using Java 11 ?

**Comment by ohumbel** [comment]
On the positive side: 

I am looking forward for 2.0.0 - it might well fix my issues in WildFly 29.x

**Comment by grgrzybek** [comment]
@ohumbel 

> On my branch, I used jetty 12.0.1. Compiling with Java 11, I get:
> [...]

Yes, Jetty 12 == JDK 17, but Jolokia should be JDK 11 and won't declare test dependency to Jetty beyond 11.

> You mentioned "waiting for Jetty 12 fixes" - so I wonder how you intend to compile using Java 11 ?

Sorry for confusion - this was for Pax Web 10, which should be the first Pax Web implementation that uses OSGi CMPN Web Specifications based on `jakarta.servlet` packages. And internally it has to be checked with Jetty 12 (on JDK 17), but by itself it should be JDK 11 friendly (at least for Tomcat and Undertow runtimes).

And only _then_ when I release Pax Web 10 I can really test Jolokia with Whiteboard on Pax Web. Before that, I'll test it on Felix HTTP with Servlet API 5/6.

**Comment by ohumbel** [comment]
@grgrzybek 
> Yes, Jetty 12 == JDK 17, but Jolokia should be JDK 11 and won't declare test dependency to Jetty beyond 11.

Thanks for the clarification! I was too aggressive updating the test dependencies then...

**Comment by ohumbel** [comment]
With all the clarifications from @grgrzybek and @tadayosi, I am now confident that the released 2.0.0 version will solve my issues. 
Therefore, I think it is safe to close this pull request.

I started with upgrading `agent/core` (now `server/core`), because I needed to embed it into WildFly 29.0.1.
Having done that, I wanted to contribute it back. Sadly not knowing that the 2.0 branch already contained the major jakarta upgrade...

Thanks again, and good luck on the future jakarta ride!

**Comment by grgrzybek** [comment]
Thanks @ohumbel for your comments - may I ask where/how are you integrating Wildfly and Jolokia?

**Comment by ohumbel** [comment]
> Thanks @ohumbel for your comments - may I ask where/how are you integrating Wildfly and Jolokia?

@grgrzybek Sure. 

In our (closed source) application, we replaced the jmx console of WildFly with a 'nicer' one based on Angular. We were able to achieve this by implementing one [JmxAgentServlet.java](https://github.com/jolokia/jolokia/files/12918281/JmxAgentServlet.java.txt) extending `AgentServlet`. 

I'll also include some screen shots: 
JMXConsoleDashboard
JMXConsole1
JMXConsole2

**Comment by grgrzybek** [comment]
Looks amazing! Thank you ;)

**Comment by tadayosi** [comment]
@ohumbel Thanks for your feedback!  Glad that the 2.0 branch works for you. You might have been already using it, but just in case there is already `2.0.0-M4` version available on Maven Central which is a build from the latest 2.0 branch. It is intended for early access like this, so it's very welcome to try it and we'd really like to hear your early feedback.

**Comment by ohumbel** [comment]
> @ohumbel Thanks for your feedback! Glad that the 2.0 branch works for you. You might have been already using it, but just in case there is already `2.0.0-M4` version available on Maven Central which is a build from the latest 2.0 branch. It is intended for early access like this, so it's very welcome to try it and we'd really like to hear your early feedback.

@tadayosi Frankly I did not integrate the 2.0 branch into our application yet. But in the meantime I integrated the 2.0.0-M4 version. I had to change the artefact name in `build.gradle`, change the import statements (roughly from `org.jolokia` to `org.jolokia.server.core`) and add the new `LogHandler` parameter to the `createRestrictor()` method. 
The WildFly container starts well and seems to work, but the client shows no results.
I have to investigate further with my colleague who better understands the client's request/response handling.

**Comment by grgrzybek** [comment]
@ohumbel 
> I have to investigate further with my colleague who better understands the client's request/response handling.

Yes, please share as much as you can - it'd really help without our effort to release Jolokia 2.0. The more issues we fix before the release, the better ;)
We are working hard on making this huge release smooth.

**Comment by tadayosi** [comment]
> The WildFly container starts well and seems to work, but the client shows no results. I have to investigate further with my colleague who better understands the client's request/response handling.

Thanks. Please feel free to file it as a new issue and we can look into it.

**Pull request closed without merging**
