### PR TITLE
Issue 532: Support java.util.Map in JMX Adapter

### LINKED ISSUE #520: Support java.util.Set type for JMX Adapter
It would be convenient to support Set type for JMX Adapter.

Currently, I'm hitting this kind of error:
```
Exception in thread "Camel DAP - Check Suspended node" java.lang.ClassCastException: class org.json.simple.JSONArray cannot be cast to class java.util.Set (org.json.simple.JSONArray is in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @6576fe71; java.util.Set is in module java.base of loader 'bootstrap')
	at jdk.proxy2/jdk.proxy2.$Proxy25.suspendedBreakpointNodeIds(Unknown Source)
	at com.github.cameltooling.dap.internal.BacklogDebuggerConnectionManager.checkSuspendedBreakpoints(BacklogDebuggerConnectionManager.java:177)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### LINKED ISSUE #532: Support java.util.Map type for JMX Adapter
I have bean that return data in from of Map<String, Boolean>

Jolokia read it correctly, but fails on parsing 

I dig into internal and problem is with type conversion 
image
it assume it is custom type with field empty 

so later in CompositeTypeConverter all fields are ignored

image

here is metadata from JMX console
image

I wonder if we missing some converter ?

### PR DESCRIPTION
**Pull request by skarsaune**
# Changes

/kind enhancement

Fixes #532 
Fixes #520

### CODE REVIEW

**Review by rhuss — COMMENTED** [review]
Looks good to me (on a quick check)!

@skarsaune could you please add an entry to changes.xml so that is shows up for the next release ? You might need to add a new release element in the XML ...

**Comment by skarsaune** [comment]
> Looks good to me (on a quick check)!
> 
> @skarsaune could you please add an entry to changes.xml so that is shows up for the next release ? You might need to add a new release element in the XML ...

Sure, version 1.7.3 ?

**Comment by rhuss** [comment]
Yeah, maybe just 1.7-SNAPSHOT for now and then we adjust it to 1.7.3 when doing the release.

**Comment by rhuss** [comment]
thanks !

**Comment by piotrwielgolaski-tomtom** [comment]
I tested this change in my case and it did not work.
After playing with changes proposed I managed to reproduce my case.
So instead of using MBeanExampleMXBean I used MBeanExampleMBean (remove X)

simple attribute access in test  shows error 
```
java.lang.AssertionError: Attribute mismatch: jolokia.test:name=MBeanExample.MapAttribute
Expected :{foo=bar}
Actual   :javax.management.openmbean.CompositeDataSupport(compositeType=javax.management.openmbean.CompositeType(name=java.util.Map,items=((itemName=empty,itemType=javax.management.openmbean.SimpleType(name=java.lang.Boolean)))),contents={empty=false})
<Click to see difference>

	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.jolokia.client.jmxadapter.JmxBridgeTest.testMBeanInfo(JmxBridgeTest.java:645)
```
it is ` JmxBridgeTest::testMBeanInfo` test case in for MBeanExampleMBean, both list and map are failing

**Comment by skarsaune** [comment]
@piotrwielgolaski-tomtom Nice! Thanks!

**Comment by skarsaune** [comment]
@piotrwielgolaski-tomtom : Sorry, I have been swamped with a legacy system that is being replaced by 30.04 in my day job. Hoping for some more progress in May :crossed_fingers:  Keep pinging me :smile:

**Comment by skarsaune** [comment]
@piotrwielgolaski-tomtom : Great! Thanks for your finding, that was really helpful. I got so carried away that I added support for Set and List as well. d07af3f51d12844b2ee5be9236c470b14628f007

**Comment by piotrwielgolaski-tomtom** [comment]
@rhuss any chance to get this merged and released?

**Review by tadayosi — APPROVED** [review]

**Comment by tadayosi** [comment]
This pull req looks good to merge already. Let me go ahead and merge it. Please let us know if any issues are found about merging it.

**Pull request merged**
