### PR TITLE
Issue 698

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Review by tadayosi — APPROVED** [review]
Great!

**Comment by tadayosi** [comment]
@grgrzybek merge is still blocked because you haven't yet followed https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification. Maybe you can consider following it to smooth the merge process.

**Comment by grgrzybek** [comment]
You're right, I thought `git commit -s` is enough...

**Comment by grgrzybek** [comment]
Ahhhh:
> Signing commits differs from signing off on a commit

**Pull request merged**
